version: 2
updates:
  # Enable version updates for workflow files
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    # labels:
    #   - "workflow dependencies"
