name: Reusable workflow for checking for changes

on:
  workflow_call:
    inputs:
      paths:
        description: 'Path to check for changed files'
        default: '.github'
        required: false
        type: string
      exclude-paths:
        description: 'Path to exclude from check'
        default: ''
        required: false
        type: string
      exclude-authors:
        description: 'Authors to exclude from check. Needs to be pipe separated'
        default: 'github-classroom\[bot\]'
        required: false
        type: string

jobs:
  change-check:
    name: Check path
    runs-on: ubuntu-latest
    steps:
      # checkout full repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Change check
        run: |
          echo "Checking for commits affecting ${{ inputs.paths }}..."
          status=0

          # check for feedback branch
          branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
          if [[ $branches == *"feedback"* ]]; then
            base="feedback"
          else
            base=$(git rev-list --max-parents=0 HEAD)
          fi

          paths=( ${{ inputs.paths }} )

          # spaces in names makes parsing the input difficult
          # exclude_authors=$(echo ${{ inputs.exclude-authors }}) # spaces in names | tr ' ' '|')

          command="git log $base..main --perl-regexp --author='^((?!${{ inputs.exclude-authors }}).)*$'"
          if [[ "${{ inputs.exclude-paths }}" != "" ]]; then
            exclude=" ':(exclude)${{ inputs.exclude-paths }}'"
          fi

          for path in ${paths[@]}; do
            command="$command $path$exclude"
            echo "Running git log command: \"$command\""
            # check for commits
            if [[ $(eval $command) ]]; then
              echo "::error file=$path:: Changes found to $path"
              echo "::group::Commits"
              eval $command
              echo "::endgroup::"
              status=1
            else
              echo "No changes found to $path"
            fi
          done

          exit $status
